name: 'infra-provisioner'
description: 'provision cluster'
author: 'yhwang'
inputs: 
  param1:
    description: 'param1'
    default: 'value1'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.param1 }}
